/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 son_goku_and_kintoun_nimbus.glb --transform 
Files: son_goku_and_kintoun_nimbus.glb [426.28KB] > /home/sam/portfolio/public/models/son_goku_and_kintoun_nimbus-transformed.glb [48.73KB] (89%)
Author: Antouss (https://sketchfab.com/antouss)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/son-goku-and-kintoun-nimbus-0e05229282e644ab978d7d9c09ab4ec2
Title: Son Goku and Kintoun Nimbus
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Son_goku_and_kintoun_nimbus(props) {
  const { nodes, materials } = useGLTF(
    "/models/son_goku_and_kintoun_nimbus-transformed.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials["7_-nimbus_0_0_0"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_3.geometry}
        material={materials["7_-staffhand_0.1_16_16"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/models/son_goku_and_kintoun_nimbus-transformed.glb");
